FROM python:3.10-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV STREAMLIT_SERVER_HEADLESS=true \
    PYTHONUNBUFFERED=1

EXPOSE 8080
CMD ["streamlit","run","appQTRR.py","--server.port=8080","--server.headless=true","--browser.gatherUsageStats=false"]
